<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Structure – Cleaning and Structuring Historical Data</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-d82805d261e7428e2a59e220d25781bb.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Cleaning and Structuring Historical Data</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Start</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-the-hour" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">The hour</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-the-hour">    
        <li>
    <a class="dropdown-item" href="../steps/01-atlas.html">
 <span class="dropdown-text">1. The atlas</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../steps/02-source.html">
 <span class="dropdown-text">2. The source</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../steps/03-structure.html">
 <span class="dropdown-text">3. Structure</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../steps/04-identity.html">
 <span class="dropdown-text">4. Clean: one person or two?</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../steps/05-ground.html">
 <span class="dropdown-text">5. Ground</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../steps/06-loop.html">
 <span class="dropdown-text">6. The map finds the errors</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../review/index.html">
 <span class="dropdown-text">Exercise: decide</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../annotate/index.html">
 <span class="dropdown-text">Exercise: mark up an entry</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../steps/07-your-data.html">
 <span class="dropdown-text">7. Your own data</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../slides.html"> 
<span class="menu-text">Slides</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../answers.html"> 
<span class="menu-text">Worked answers</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../glossary.html"> 
<span class="menu-text">Glossary</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-more" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">More</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-more">    
        <li>
    <a class="dropdown-item" href="../handout.html">
 <span class="dropdown-text">Printable handout</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../setup.html">
 <span class="dropdown-text">Run it yourself</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../presenter.html">
 <span class="dropdown-text">Presenter notes</span></a>
  </li>  
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#the-shape-of-it" id="toc-the-shape-of-it" class="nav-link active" data-scroll-target="#the-shape-of-it">The shape of it</a></li>
  <li><a href="#the-schema" id="toc-the-schema" class="nav-link" data-scroll-target="#the-schema">The schema</a></li>
  <li><a href="#the-prompt-exactly-as-sent" id="toc-the-prompt-exactly-as-sent" class="nav-link" data-scroll-target="#the-prompt-exactly-as-sent">The prompt, exactly as sent</a></li>
  <li><a href="#the-overnight-run" id="toc-the-overnight-run" class="nav-link" data-scroll-target="#the-overnight-run">The overnight run</a></li>
  <li><a href="#two-kinds-of-model" id="toc-two-kinds-of-model" class="nav-link" data-scroll-target="#two-kinds-of-model">Two kinds of model</a></li>
  <li><a href="#what-came-back" id="toc-what-came-back" class="nav-link" data-scroll-target="#what-came-back">What came back</a></li>
  <li><a href="#the-audit" id="toc-the-audit" class="nav-link" data-scroll-target="#the-audit">The audit</a></li>
  <li><a href="#why-the-fix-was-not-a-bigger-model" id="toc-why-the-fix-was-not-a-bigger-model" class="nav-link" data-scroll-target="#why-the-fix-was-not-a-bigger-model">Why the fix was not a bigger model</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Structure</h1>
<p class="subtitle lead">Minutes 12–22. What is a record here? Python takes the regular entries, a cheap model takes the rest overnight, Python checks the result; you decide what counts as an event.</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="callout callout-style-default callout-note callout-titled" title="Terms on this page">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Terms on this page
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li><strong>JSON</strong>: a plain-text format for a record: named fields in braces, lists in brackets (see the glossary for Trimen’s).</li>
<li><strong>prompt</strong>: the written instructions sent to the model with each entry.</li>
<li><strong>regex grammar</strong>: pattern rules that match text by its shape, written in Python; the deterministic first tier.</li>
<li><strong>validator</strong>: Python that checks every place and year the model wrote against the source and drops what is not there.</li>
<li><strong>post-normaliser</strong>: Python that applies the systematic fixes found by the audit, logging each change.</li>
<li><strong>vLLM</strong>: an open-source server that runs an open model on a GPU and answers like a commercial API.</li>
<li><strong>GPU</strong>: the graphics card the model runs on; the model has to fit in its memory.</li>
<li><strong>token</strong>: the unit a model reads and writes in, roughly three-quarters of a word.</li>
<li><strong>reasoning mode</strong>: a setting where the model writes out its thinking before answering; off here, because it spent the budget and returned nothing.</li>
<li><strong>frontier model / open model</strong>: a commercial model such as Claude or Gemini, run by its maker; an open model such as Qwen, whose weights you can download and run yourself.</li>
<li><strong>deterministic</strong>: done by fixed rules, so the same input always gives the same output; no model involved.</li>
</ul>
<p>All terms: <a href="../glossary.html">glossary</a>.</p>
</div>
</div>
</div>
<section id="the-shape-of-it" class="level2">
<h2 class="anchored" data-anchor-id="the-shape-of-it">The shape of it</h2>
<p>Structuring the biographies was never “send them to a model”. It was a hybrid, in three parts, and the same three parts ran twice: once for the Colonial Office List in June 2026, once for the India Office List a week later.</p>
<ol type="1">
<li><strong>Python first.</strong> A regex grammar for the printed entry shape parses what it can. It is all-or-nothing: if any clause containing a year fails to parse cleanly, the whole entry is refused rather than half-parsed. A second Python pass expands the abbreviations it recognises (“Feb.” to “February”, “acctnt.” to “accountant”) and leaves everything else exactly as printed.</li>
<li><strong>A model for what Python cannot do.</strong> Binding position to place to time span across run-on, elided, “ditto” and concurrent clauses. One entry in, one JSON object out. For the Colonial Office List the first residue went to a batch API with a cheap commercial model; the bulk of both corpora went to an open model on a university GPU.</li>
<li><strong>Python again.</strong> A validator that checks every place and year the model emitted against the source text and drops what it cannot find there. Then a post-normalisation pass that applies the deterministic fixes found by the audit, logging every change.</li>
</ol>
</section>
<section id="the-schema" class="level2">
<h2 class="anchored" data-anchor-id="the-schema">The schema</h2>
<p>One object per entry: <code>surname</code>, <code>given_names</code>, <code>birth_year</code> (only if printed), <code>education</code>, <code>honours</code> with award years, <code>events</code>, and <code>terminal</code>. One event per posting: <code>position</code> and <code>place</code> as printed, <code>year_start</code>, <code>year_end</code>, <code>place_inherited</code>, <code>is_acting</code>, and <code>civil</code> or <code>military</code>. The agent and the historian settled it on a sample before any batch ran.</p>
</section>
<section id="the-prompt-exactly-as-sent" class="level2">
<h2 class="anchored" data-anchor-id="the-prompt-exactly-as-sent">The prompt, exactly as sent</h2>
<p>The system message for every one of the 65,000 entries (<a href="../outputs/structure/extraction-prompt.txt">file</a>):</p>
<pre class="text"><code>You convert ONE printed Colonial Office List biographical entry into a JSON career record. Extract ONLY what is printed; never invent or infer facts.
Rules:
- events: one object per distinct posting. EXPLODE compound/concurrent clauses into separate events (e.g. 'reg.-gen., 1887, and M.L.C., 1889' = two events; 'ag. comsnr., 1915-16; and from 1919' = two events).
- position: as printed (the normalized expansion is fine), e.g. 'assistant colonial secretary'.
- place: the colony, territory, OR locality named in the clause, AS PRINTED (e.g. 'Ceylon', 'Negombo', 'N. Nigeria'). If the clause names no place, carry over the previous clause's place and set place_inherited=true; do NOT guess or upgrade a locality to its parent colony — record exactly what is printed. Inheritance stops when a transfer is stated.
- year_start/year_end: the posting's years; year_end null if a single year.
- is_acting: true when the post is acting ('ag.'/'acting').
- org_type: 'military' for army/navy/regiment/expedition/campaign postings, else 'civil'.
- honours: decorations/orders with their AWARD year if printed in parentheses (e.g. 'C.M.G. (1905)'); these award-years are NOT career events.
- birth_year: only if explicitly printed ('B. 1872'); else null. NEVER infer from the earliest career date.
- education: the 'ed. ...' string as one metadata string; university class honours stay here, NOT as events.
- terminal: {kind: retired|resigned|died|pensioned|other, year} if the entry states the career ended, else null.

Return ONE JSON object with EXACTLY these top-level keys: surname, given_names, birth_year, education, honours, events, terminal. Split the headword into surname + given_names (no 'name'/'person' key). Each honour is {"award": str, "year": int|null} (no 'decoration'/'order' key).
</code></pre>
<p>The user message is the entry alone, after the abbreviation pass. Trimen’s 1889 entry goes in like this (<a href="../outputs/structure/extraction-user-message-example.txt">file</a>):</p>
<pre class="text"><code>TRIMEN, HENRY, M.B. (Lond.), F.R.S., F.L.S. —Formerly lecturer on botany at St. Mary's Hospital, London, 1867 to 1875; was senior assistant to department of botany, British Museum, 1869 to 1879; director Royal Botanical Gardens, Ceylon, February, 1880; author of numerous works and papers on pure and applied botany.
</code></pre>
<p>Three things to notice. Every rule in the list exists because an earlier run broke it; the rule about birth years is there because a model had been inferring them from the first appointment. The last paragraph pins the key names, because a bake-off found the model drifting to <code>name</code> and <code>decoration</code> without it. And nothing in the prompt is about the historical question; it is entirely about what the page says and how to hold it.</p>
</section>
<section id="the-overnight-run" class="level2">
<h2 class="anchored" data-anchor-id="the-overnight-run">The overnight run</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Colonial Office List</th>
<th>India Office List</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Model</td>
<td>Qwen3.6-35B-A3B, served by vLLM on a university GPU box</td>
<td>same</td>
</tr>
<tr class="even">
<td>Settings</td>
<td>temperature 0, reasoning off, 8 to 16 workers, 4 retries</td>
<td>same</td>
</tr>
<tr class="odd">
<td>Entries</td>
<td>34,743</td>
<td>30,496</td>
</tr>
<tr class="even">
<td>Rate once warm</td>
<td>about 1 a second</td>
<td>1.03 a second</td>
</tr>
<tr class="odd">
<td>Elapsed</td>
<td>about a day including setup, 19–20 June</td>
<td>8.24 hours, overnight 25–26 June</td>
</tr>
<tr class="even">
<td>Failed to return valid JSON</td>
<td></td>
<td>55, under 0.2 per cent</td>
</tr>
</tbody>
</table>
<p>The handoff note records the setting that matters most: reasoning off. With it on, long entries eat the token budget and return no JSON, a 67 per cent failure rate. Thinking off, temperature zero: the same finding every run on this corpus has made.</p>
<p>The India Office List needed one new piece of code, a Python segmenter for its different OCR format, written that morning. The prompt, the model, the validator and the post-normaliser were reused unchanged through one environment variable. The graph was published that afternoon.</p>
</section>
<section id="two-kinds-of-model" class="level2">
<h2 class="anchored" data-anchor-id="two-kinds-of-model">Two kinds of model</h2>
<p>A frontier model, in session as the coding agent, structured about 200 entries by hand as the reference set and wrote everything in the list above. The open model inside the script read the corpus. Every record says which path produced it. The runbook for the in-session loop is <a href="../outputs/structure/structuring-loop-runbook.md">saved</a>.</p>
</section>
<section id="what-came-back" class="level2">
<h2 class="anchored" data-anchor-id="what-came-back">What came back</h2>
<p>Trimen’s entry, structured (<a href="../outputs/structure/trimen-structured.json">saved</a>):</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>position</th>
<th>place</th>
<th>years</th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>lecturer on botany</td>
<td>London</td>
<td>1867–1875</td>
<td></td>
</tr>
<tr class="even">
<td>senior assistant to department of botany</td>
<td>British Museum</td>
<td>1869–1879</td>
<td>overlaps the first: two concurrent posts, two events</td>
</tr>
<tr class="odd">
<td>director Royal Botanical Gardens</td>
<td>Ceylon</td>
<td>1880–</td>
<td></td>
</tr>
</tbody>
</table>
<p>Plus <code>education: "M.B. (Lond.)"</code>, two honours without years, no birth year, no terminal event. In the published graph the first and third events are placed; “British Museum” is an institution, not a place, and stays unplaced.</p>
</section>
<section id="the-audit" class="level2">
<h2 class="anchored" data-anchor-id="the-audit">The audit</h2>
<p>Structured records were read against their source by a reviewer model, in three rounds, and the findings categorised (<a href="../outputs/audit/struct-error-catalog.md">catalogue</a>, <a href="../outputs/audit/every10-reviewed-pairs.json">round 1 pairs</a>). The figures are before the post-normaliser described below:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Round</th>
<th>Sample</th>
<th>Fully clean</th>
<th>Major error</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>every tenth of the first 1,859 records: 186</td>
<td>129 (69%)</td>
<td>8 (about 3%)</td>
</tr>
<tr class="even">
<td>2</td>
<td>100 spread across the corpus</td>
<td>51 (51%)</td>
<td>9 (about 9%)</td>
</tr>
<tr class="odd">
<td>3</td>
<td>300 spread across the corpus</td>
<td>about 149 (50%)</td>
<td>not tallied</td>
</tr>
</tbody>
</table>
<p>Round 1 was front-loaded on early, simple entries; the later rounds reach the dense twentieth-century careers and the peerage entries, and are the better estimate. A model did the reading in all three; the examples below were checked by hand.</p>
<p>Three of the findings, source beside record (<a href="../outputs/structure/audit-examples.json">saved</a>):</p>
<p><strong>The ditto that was not resolved.</strong> Balmer’s last clause, “senr. dep. P.M.G., do., 1935”, came back with <code>place: "do."</code>. The rule says inherit; the model copied the abbreviation.</p>
<p><strong>The appointment date that became a birth year.</strong> “BLAKELY, DONALD QUENTIN.—Clk., atty.-gen.’s off., B. Honduras, Apl., 1898.” came back with <code>birth_year: 1898</code> and an event with no year. The prompt forbids exactly this. The same record expanded “off.” to “officer” instead of “office”.</p>
<p><strong>The knighthood split in two.</strong> “KT. BACH. (1920)” came back as two honours, <code>KT</code> and <code>BACH (1920)</code>. Three records in the sample did the same.</p>
</section>
<section id="why-the-fix-was-not-a-bigger-model" class="level2">
<h2 class="anchored" data-anchor-id="why-the-fix-was-not-a-bigger-model">Why the fix was not a bigger model</h2>
<p>The errors are not random. They are a handful of systematic patterns: a short list of abbreviations mis-expanded the same way every time, ditto marks left literal, one compound honour split, “mentioned in despatches” dropped. Each has a deterministic fix, and those fixes are the post-normalisation pass: merge <code>KT</code> + <code>BACH</code> into Knight Bachelor; forward-fill a “do.” place from the previous event and set the flag; strip honorifics folded into given names; “officer in chief” back to “officer in charge”; drop a military tag with no military signal in the position. Every change is appended to a list on the record, so nothing is silent. The “off.” expansion is fixed one step earlier, by not pre-expanding ambiguous abbreviations at all.</p>
<p>A frontier model on every entry would have cost more, taken longer, and still needed the audit.</p>
<p><strong>You decide:</strong> what is an event. Whether an acting appointment is a posting. Whether “called to the bar, 1879” belongs in the career. Whether “leader of leg. coun. from 1906 to 1911” is a position or a description. The prompt records those decisions; the audit checks whether the model kept them; the post-normaliser enforces the ones that can be enforced.</p>
<p>Next: <a href="../steps/04-identity.html">Clean: one person or two?</a></p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
          // target, if specified
          link.setAttribute("target", "_blank");
          if (link.getAttribute("rel") === null) {
            link.setAttribute("rel", "noopener");
          }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Jim Clifford, University of Saskatchewan. Draft materials; sources credited on each page.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>Data: Imperial Careers (CC0), jimclifford.ca/col_matching</p>
</div>
  </div>
</footer>




</body></html>