<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Research packet: the Trimen network – Cleaning and Structuring Historical Data</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-d82805d261e7428e2a59e220d25781bb.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Cleaning and Structuring Historical Data</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Start</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-the-hour" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">The hour</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-the-hour">    
        <li>
    <a class="dropdown-item" href="./steps/01-question.html">
 <span class="dropdown-text">1. The question</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./steps/02-structure-extract.html">
 <span class="dropdown-text">2. Structure and extract</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./steps/03-candidates.html">
 <span class="dropdown-text">3. Candidate identities</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./steps/04-review.html">
 <span class="dropdown-text">4. Review (exercise)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./steps/05-revise.html">
 <span class="dropdown-text">5. Revise the process</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./steps/06-connect.html">
 <span class="dropdown-text">6. Connect collections</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./steps/07-your-data.html">
 <span class="dropdown-text">7. Your own data</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="./answers.html"> 
<span class="menu-text">Worked answers</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./review/index.html"> 
<span class="menu-text">Exercise</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./setup.html"> 
<span class="menu-text">Run it yourself</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./presenter.html"> 
<span class="menu-text">Presenter notes</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./packet.html" aria-current="page"> 
<span class="menu-text">Research packet</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#trimen-cinchona-and-the-expansion-of-a-research-question" id="toc-trimen-cinchona-and-the-expansion-of-a-research-question" class="nav-link active" data-scroll-target="#trimen-cinchona-and-the-expansion-of-a-research-question">Trimen, cinchona, and the expansion of a research question</a>
  <ul class="collapse">
  <li><a href="#the-passages-to-use" id="toc-the-passages-to-use" class="nav-link" data-scroll-target="#the-passages-to-use">The passages to use</a></li>
  <li><a href="#grounding-people-plants-and-places" id="toc-grounding-people-plants-and-places" class="nav-link" data-scroll-target="#grounding-people-plants-and-places">Grounding people, plants and places</a></li>
  <li><a href="#historical-classification-is-part-of-the-evidence" id="toc-historical-classification-is-part-of-the-evidence" class="nav-link" data-scroll-target="#historical-classification-is-part-of-the-evidence">Historical classification is part of the evidence</a></li>
  <li><a href="#correspondence-as-the-next-research-branch" id="toc-correspondence-as-the-next-research-branch" class="nav-link" data-scroll-target="#correspondence-as-the-next-research-branch">Correspondence as the next research branch</a></li>
  <li><a href="#reuse-and-remaining-preparation" id="toc-reuse-and-remaining-preparation" class="nav-link" data-scroll-target="#reuse-and-remaining-preparation">Reuse and remaining preparation</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Research packet: the Trimen network</h1>
<p class="subtitle lead">Follow-up material. Candidate links, attributed claims and catalogue records, all awaiting human review.</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>The tables below live in <code>research/trimen-network/</code>: <a href="research/trimen-network/entities.csv">entities.csv</a>, <a href="research/trimen-network/claims.csv">claims.csv</a>, <a href="research/trimen-network/letters.csv">letters.csv</a>, <a href="research/trimen-network/taxonomy.csv">taxonomy.csv</a>, <a href="research/trimen-network/archival-leads.csv">archival-leads.csv</a>, with JSON equivalents, the seven frozen article records in <code>sources/</code>, and the cached Wikidata responses in <code>raw/</code>. The packet’s own description follows.</p>
<section id="trimen-cinchona-and-the-expansion-of-a-research-question" class="level1">
<h1>Trimen, cinchona, and the expansion of a research question</h1>
<p>Working research packet, 6 October 2026. Prepared for the AI and History workshop. This is a separate, assistant-curated draft for Jim’s review; it does not update Tropical’s production identities or the RA’s decisions.</p>
<p>The starting question is concrete: who is Henry Trimen connected to in <em>The Tropical Agriculturist</em>, and what can we establish about those connections? The answer leads from a dispute with John Eliot Howard to planters, seed suppliers, botanical gardens, pharmaceutical manufacturing, and correspondence. Shared identifiers help connect the records, but the historical claims need their own evidence.</p>
<section id="the-passages-to-use" class="level2">
<h2 class="anchored" data-anchor-id="the-passages-to-use">The passages to use</h2>
<p>Seven frozen article records are in <code>sources/</code>. Each retains the Tropical article ID, OCR text, page links, and source segments. The July 1883 opening on scan n44 has been visually inspected. Other passages have been read in OCR and still need comparison with their scans before presenting a final transcription. The parent search file contains 72 articles with both surnames; that is a discovery set, not 72 verified relationships between Henry Trimen and John Eliot Howard.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Source</th>
<th>Passage</th>
<th>Why it matters</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>S01</td>
<td><a href="https://archive.org/details/tropicalagricult1188ceyl/page/n139/mode/1up">“Mr.&nbsp;Eliot Howard Extinguishing C. Pubescentis How.”, July 1881, pp.&nbsp;114–115</a></td>
<td>Howard disclaims having created a species under this name. The editorial also criticizes Clements Markham’s account of hybrid parentage.</td>
</tr>
<tr class="even">
<td>S02</td>
<td><a href="https://archive.org/details/tropicalagricult18831884colo/page/n44/mode/1up">“The Wars of the Quinologists”, July 1883, pp.&nbsp;27–28</a></td>
<td>The journal explicitly presents a dispute among Howard, Trimen, and Moens. A short opening for the workshop.</td>
</tr>
<tr class="odd">
<td>S03</td>
<td><a href="https://archive.org/details/tropicalagricult18831884colo/page/n54/mode/1up">“Dr.&nbsp;Trimen’s Ledgeriana: Mr.&nbsp;T. N. Christie to the Rescue”, p.&nbsp;37</a></td>
<td>Christie’s letter of 7 June 1883 traces the illustrated plant through McIvor’s seed, his nursery, and Agar’s planting. This is Christie’s asserted provenance.</td>
</tr>
<tr class="even">
<td>S04</td>
<td><a href="https://archive.org/details/tropicalagricult18831884colo/page/n83/mode/1up">“Dr.&nbsp;Trimen’s Typical Ledgeriana Tree”, p.&nbsp;66</a></td>
<td>Agar’s letter of 22 June 1883 distinguishes the illustrated tree from other trees whose bark Campbell sent to Howard. Excellent material for checking a model’s proposed relationship.</td>
</tr>
<tr class="odd">
<td>S05</td>
<td><a href="https://archive.org/details/tropicalagricult18831884colo/page/n470/mode/1up">“The Cinchona Calisaya (or Ledgeriana) Discussion”, December 1883, p.&nbsp;453</a></td>
<td>Howard’s quoted letter and Trimen’s cover letter connect people, publications and places. Trimen writes from Royal Botanic Gardens, Peradeniya on 21 November.</td>
</tr>
<tr class="even">
<td>S06</td>
<td><a href="https://archive.org/details/tropicalagricult18831884colo/page/n470/mode/1up">“The Botany of Cinchona Ledgeriana”, December 1883, pp.&nbsp;453–455</a></td>
<td>Trimen’s argument, dated 29 October, reports competing identifications and distinguishes botanical characters from chemical yield.</td>
</tr>
<tr class="odd">
<td>S07</td>
<td><a href="https://archive.org/details/tropical-agriculturist_april-june-1943_99_2/page/n34/mode/1up">“History of Cinchona Culture in Ceylon”, April–June 1943, beginning p.&nbsp;91</a></td>
<td>A retrospective account brings in Markham, Spruce, plant movements, Peradeniya and Hakgala. Publication date must remain separate from the events described.</td>
</tr>
</tbody>
</table>
<p>The direct Trimen–Howard connection is a published disagreement, not merely article co-occurrence. Trimen’s reply goes to the editor of the <em>Pharmaceutical Journal</em> and is forwarded for publication in Ceylon; it should not be recoded as a private letter addressed to Howard.</p>
</section>
<section id="grounding-people-plants-and-places" class="level2">
<h2 class="anchored" data-anchor-id="grounding-people-plants-and-places">Grounding people, plants and places</h2>
<p><code>entities.csv</code> and <code>entities.json</code> contain 49 local entities, with candidate QIDs where authority records have been checked. <code>record_checked</code> means that the Wikidata item was retrieved and examined. It does not mean that every historical occurrence of that name has been matched, that every statement on the item is trustworthy, or that a human has approved the proposal. Every human-review field remains pending.</p>
<p>The people include Henry Trimen (Q2462643), John Eliot Howard (Q3181423), Clements Markham (Q507802), Moens (Q21340893), McIvor (Q21520254), Charles Ledger (Q963818), Weddell (Q983408), Joseph Dalton Hooker (Q157501), Fitch (Q1102060), and Richard Spruce (Q1349394). The correspondence adds Roland Trimen (Q932702), Thiselton-Dyer (Q2065240), and Daniel Morris (Q20733957). Surname-only assignments remain proposals supported by context.</p>
<p>Thomas North Christie and Walter Agar retain local identifiers. No suitable Wikidata match was established in the searches performed. Absence from those results does not demonstrate that an item does not exist. Christie must not be merged with Thomas Christy on spelling similarity. Moens’s cached authority labels and aliases disagree about his given name, so the packet retains initials. Trimen’s account also mentions an unnamed servant of Ledger; keeping a local record prevents that person’s involvement from disappearing merely because the source supplies no personal name.</p>
<p>Royal Botanic Gardens, Peradeniya (Q3119056) is explicit in the 1883 cover letter. Peradeniya as a locality has a separate candidate, Q489744. Likewise, Kew’s garden site and the research institution have distinct items. The bare word Hakgala in a catalogue address does not establish that the sender was inside the botanical garden. Estates such as St.&nbsp;Andrew’s, Mahanillu and Yarrow remain local records without invented coordinates.</p>
<p>Howards and Sons (Q123413890) provides a possible industrial branch. The archive catalogue for collection ACC/1037 describes the firm’s pharmaceutical business and its Stratford headquarters before the move to Ilford. This is external contextual evidence, kept distinct from the Tropical passages. <a href="https://atom.aim25.com/index.php/howards-and-sons-chemists?sf_culture=en">Howards and Sons archive catalogue</a></p>
<p><strong>West Ham is a useful correction to a model’s reasoning.</strong> The label “County Borough of West Ham” initially suggested that Q5177625 would be too late for the 1883 setting. Jim pointed out that the item includes the local board of health. Its statements explicitly cover that form from 1856 to 1886. The packet therefore retains the QID for West Ham local government, with the appropriate period and label. The county-borough start qualifier currently says 1 April 1899, while the municipal-borough end says 31 March 1889; these unreferenced statements require investigation. Accepting an identity link does not require accepting all attached dates. <a href="https://www.wikidata.org/wiki/Q5177625">Wikidata record</a></p>
</section>
<section id="historical-classification-is-part-of-the-evidence" class="level2">
<h2 class="anchored" data-anchor-id="historical-classification-is-part-of-the-evidence">Historical classification is part of the evidence</h2>
<p>Some historical identifications may have been wrong. The data must preserve enough detail to examine that question: who identified which plant, under what name, when, and on what evidence? Trimen’s claim that several differently named plants were botanically identical belongs in the dataset as his argument, rather than as an automatic correction to all earlier records.</p>
<p><code>claims.csv</code> and <code>claims.json</code> contain 14 proposed relationships with exact OCR evidence, attribution and review notes. The illustrated tree and its neighbouring trees have separate local IDs. Agar says that bark from some trees went to Howard, while bark from the illustrated tree remained in his possession. An extraction that says Howard analysed the illustrated tree would overstate the evidence. The source’s word “typical” also does not by itself establish nomenclatural type status.</p>
<p>There are three separate questions to retain:</p>
<ol type="1">
<li>Which name did a historical actor use?</li>
<li>Which specimen or group of plants did that actor identify with that name?</li>
<li>How does a current authority treat the name?</li>
</ol>
<p>Kew’s Plants of the World Online currently treats <em>Cinchona ledgeriana</em> as a synonym of <em>C. calisaya</em>, and <em>C. succirubra</em> as a synonym of <em>C. pubescens</em>. These treatments are recorded separately in <code>taxonomy.csv</code>; they do not settle whether Howard or Trimen correctly identified a particular historical tree. <a href="https://powo.science.kew.org/taxon/urn:lsid:ipni.org:names:746808-1">Ledgeriana record</a>, <a href="https://powo.science.kew.org/taxon/urn:lsid:ipni.org:names:746904-1">succirubra record</a></p>
<p>The 1881 Howard letter makes an especially useful case. It distinguishes a hybrid that people were calling “C. pubescens How.” from an already established species with different characters. Mapping both occurrences directly to Q164574 would erase the issue the letter discusses. A separate local historical-name record preserves it.</p>
<p>Bark, cinchona alkaloids and quinine also have separate records. Pure quinine and sulphate of quinine are not interchangeable measurements. The packet includes only a selection of the plant names Jim supplied; unexamined species, categories and taxonomy templates have not been inserted as if they were all participants in this dispute.</p>
</section>
<section id="correspondence-as-the-next-research-branch" class="level2">
<h2 class="anchored" data-anchor-id="correspondence-as-the-next-research-branch">Correspondence as the next research branch</h2>
<p><code>letters.csv</code> and <code>letters.json</code> transcribe 25 distinct catalogue entries supplied by Jim, spanning 1893–1896. Repeated display titles in the pasted list have been collapsed. There are 24 letters attributed to Henry: 23 to Thiselton-Dyer and one to Daniel Morris. One is attributed to Roland Trimen, writing to Thiselton-Dyer from 5 Lancaster Street on 31 December 1896.</p>
<p>These records establish catalogue-described correspondence, dates, origins, folios, and page/image counts. They do not establish what the letters discuss. The list is a selection, not a complete correspondence census. Repository URLs for individual entries have not yet been matched.</p>
<p>Jim also supplied <a href="https://plants.jstor.org/stable/10.5555/al.ap.visual.kdcas1413">kdcas1413</a> and <a href="https://plants.jstor.org/stable/10.5555/al.ap.visual.kdcas1411">kdcas1411</a>. These are retained separately in <code>archival-leads.csv</code>. The records could not be retrieved during this check; their subjects and correspondence dates remain unverified. No association has been inferred from their sequential identifiers.</p>
<p>For the workshop, show this branch briefly as the next question opened by the research. Reading a whole correspondence collection belongs in the follow-up materials, not the hour’s core exercise.</p>
</section>
<section id="reuse-and-remaining-preparation" class="level2">
<h2 class="anchored" data-anchor-id="reuse-and-remaining-preparation">Reuse and remaining preparation</h2>
<p>Run <code>python3 scripts/build_trimen_workshop.py</code> from the workshop repository to rebuild the CSV and JSON files. It validates exact evidence strings, referenced local entities, unique correspondence IDs, and the presence of cached candidate authority records. <code>manifest.json</code> records the hash of the frozen search input. The public retrieval helper, <code>scripts/ground_trimen.py</code>, caches full Wikidata responses under <code>raw/</code>, including qualifiers, references and retrieval timestamps.</p>
<p>Before presenting, compare the selected exercise passage with its scan, review the proposed identities and claims, and attach a small Colonial Office List excerpt for Henry’s career. Keep the broader research packet available on GitHub, but limit the participant exercise to a short passage and a few decisions. The packet is saved locally; this workspace is not yet a Git repository and nothing has been published.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
          // target, if specified
          link.setAttribute("target", "_blank");
          if (link.getAttribute("rel") === null) {
            link.setAttribute("rel", "noopener");
          }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Jim Clifford, University of Saskatchewan. Draft materials; sources credited on each page.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>Source text: archive.org scans of The Tropical Agriculturist.</p>
</div>
  </div>
</footer>




</body></html>