<!DOCTYPE html>
<html lang="en"><head>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-html/tabby.min.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-b53751a350365c71b6c909e95f209ed1.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.6.42">

  <meta name="author" content="Jim Clifford, University of Saskatchewan">
  <meta name="dcterms.date" content="2026-10-15">
  <title>Cleaning and Structuring Historical Data – Cleaning, Structuring and Grounding Historical Data</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="site_libs/revealjs/dist/theme/quarto-731aca3fa2b26cb952c064d9e94a4161.css">
  <link href="site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-dark">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" data-background-image="images/atlas-screenshot.png" data-background-opacity="0.15" class="quarto-title-block center">
  <h1 class="title">Cleaning, Structuring and Grounding Historical Data</h1>
  <p class="subtitle">One dataset, start to finish, with a coding agent</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Jim Clifford, University of Saskatchewan 
</div>
</div>
</div>

  <p class="date">15 October 2026</p>
</section>
<section id="mobility-video" class="slide level2 video-slide" data-background-color="#15161a">
<h2></h2>
<video data-autoplay="" controls="" muted="" playsinline="" preload="metadata" poster="images/combined-mobility-frame.jpg" aria-label="Animated atlas of imperial career postings">
  <source src="https://jimclifford.ca/col_matching/combined_mobility.mp4" type="video/mp4">
  <source src="media/combined-mobility.webm" type="video/webm">
  Your browser cannot play this video. Use the direct link below.
</video>
<p class="video-link"><a href="https://jimclifford.ca/col_matching/combined_mobility.mp4" target="_blank" rel="noopener">Open the video directly</a> · Earlier atlas export</p>
<aside class="notes">
<p>0–1. Let the 56-second video run. It is an earlier export; the dated build counts in the deck supersede its caption. These are sequences of recorded postings, not observed travel routes. The video starts muted when this slide opens; use Play or Replay in its controls if needed. The direct link opens the MP4 separately. Use the downloaded copy if the network fails.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="what-one-arc-needs" class="slide level2 smaller">
<h2>What one arc needs</h2>
<blockquote>
<p>WODEHOUSE, SIR PHILIP E.—Entered the Ceylon civil service as a writer, May, 1828; … superintendent of Honduras, 1851; … governor of British Guiana; … in 1861 was appointed governor of the Cape of Good Hope.</p>
</blockquote>
<table class="caption-top">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Printed wording</th>
<th>Event</th>
<th>Historical place</th>
<th>Plotting seat</th>
<th>Year</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>writer, May, 1828</td>
<td>writer</td>
<td>British Ceylon</td>
<td>Colombo</td>
<td>1828</td>
</tr>
<tr class="even">
<td>superintendent of Honduras</td>
<td>superintendent</td>
<td>British Honduras</td>
<td>Belize</td>
<td>1851</td>
</tr>
<tr class="odd">
<td>governor of British Guiana</td>
<td>governor</td>
<td>British Guiana</td>
<td>Georgetown</td>
<td>1854</td>
</tr>
<tr class="even">
<td>governor of the Cape of Good Hope</td>
<td>governor</td>
<td>Cape Colony</td>
<td>Cape Town</td>
<td>1861</td>
</tr>
<tr class="odd">
<td>governor of Bombay (India Office List)</td>
<td>governor</td>
<td>Bombay Presidency</td>
<td>Bombay</td>
<td>1872–77</td>
</tr>
</tbody>
</table>
<div class="flow">
  <div class="node"><b>Printed clause</b><span>“governor of the Cape of Good Hope”</span></div>
  <div class="arrow">→</div>
  <div class="node"><b>Event</b><span>governor · 1861</span></div>
  <div class="arrow">→</div>
  <div class="node blue"><b>Checked place identifier</b><span>Cape Colony, a Wikidata item</span></div>
  <div class="arrow">→</div>
  <div class="node blue"><b>Plotting seat</b><span>Cape Town: a proxy, not a residence</span></div>
  <div class="arrow">→</div>
  <div class="node"><b>Arc</b><span>British Guiana → Cape</span></div>
</div>
<aside class="notes">
<p>1–3. Source is the 1867 Colonial Office List; Bombay comes from the India Office List. The full table, identifiers and trace are on step 1. “Honduras” to “British Honduras” is an interpretation, kept separately from printed wording. A capital is a plotting proxy, not evidence of residence. Wodehouse is a checked example of the cross-service match; the other bridges need review.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="cross-service-career" class="slide level2">
<h2>One career across two Lists</h2>
<div class="columns">
<div class="column" style="width:42%;">
<p><span class="blue">Colonial Office List</span><br>
Ceylon → Honduras → British Guiana → Cape</p>
<p><span class="gold">India Office List</span><br>
Bombay, 1872–77</p>
<p>Linking the entries follows one career across two administrative collections.</p>
<p><strong>What becomes visible when we read the two Lists together?</strong></p>
<p><a href="https://jimclifford.ca/col_matching/?p=kgp_col1878-p447b3">Open Wodehouse’s career</a></p>
</div><div class="column" style="width:58%;">
<p><img data-src="images/atlas-wodehouse-repaired.png" alt="Current atlas view of Philip Wodehouse's career, with arcs from Ceylon to Honduras, British Guiana, the Cape and Bombay, and a dated list of postings"></p>
<p><span class="caption">Current public atlas, after the 7–8 October repairs</span></p>
</div></div>
<aside class="notes">
<p>3–4. Lead with the historical use: a reader of either List alone sees part of this career. The checked link brings those parts together. This is a selection of postings, not the full itinerary. The public example reflects the repairs published and checked on 7–8 October. The supporting page retains the earlier Wodehouse errors and their corrections as optional teaching material. This one checked link does not establish that all proposed cross-service links are correct.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="what-the-records-make-visible" class="slide level2 smaller">
<h2>What the records make visible</h2>
<div class="stats">
  <div class="stat"><span class="num">46,926</span><span class="lbl">person records across two Lists</span></div>
  <div class="stat"><span class="num">305,164</span><span class="lbl">career events</span></div>
  <div class="stat"><span class="num">211,581</span><span class="lbl">events linked to a Wikidata place</span></div>
  <div class="stat"><span class="num">36,431</span><span class="lbl">arcs for 16,287 roster records with moves (September build)</span></div>
</div>
<ul>
<li>Administrative accounts of careers, offices and honours.</li>
<li>Person counts resolved within each List; their sum includes cross-service overlap.</li>
<li>Seats used for plotting; arcs connect postings, not observed journeys.</li>
</ul>
<p><strong>Whose careers does this source make easy to see? Whose does it leave out?</strong></p>
<aside class="notes">
<p>4–5. Ask for one response, room or chat. Official records make the administration’s categories visible, not everyone who worked for or lived under it. Grounding covers 1,066 of 27,526 CO people, about 3.9%; person links are selective, not representative. Event-to-place coverage is a different measure. Stats copied from 4 September.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="three-questions" class="slide level2">
<h2>Three questions</h2>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>The question</th>
<th>You decide</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="gold">Structure</span></td>
<td>What is a record here?</td>
<td>What counts as an event</td>
</tr>
<tr class="even">
<td><span class="gold">Clean</span></td>
<td>One person or two?</td>
<td>Merge, keep apart, review</td>
</tr>
<tr class="odd">
<td><span class="gold">Ground</span></td>
<td>Which place, which person?</td>
<td>Supported, unresolved, wrong</td>
</tr>
</tbody>
</table>
<div class="flow">
  <div class="node blue"><b>OCR text</b><span>85 volumes</span></div>
  <div class="arrow">→</div>
  <div class="node"><b>Structure</b><span>entries → events</span></div>
  <div class="arrow">→</div>
  <div class="node"><b>Clean</b><span>editions → people</span></div>
  <div class="arrow">→</div>
  <div class="node"><b>Ground</b><span>names → identifiers</span></div>
  <div class="arrow">→</div>
  <div class="node blue"><b>Graph and atlas</b><span>visualise, then look</span></div>
</div>
<div class="loopback">↺ See · Fix the rule · Rerun for every affected record</div>
<aside class="notes">
<p>5–7. A historian owns the decisions; the agent writes scripts that apply them at scale. Today participants mark up an entry and make three decisions. We start after OCR. The published description mentions Britannica OCR tools; this session uses existing olmOCR output and does not demonstrate those tools. Your own dataset is the take-home application. Put the site and exercise links in Zoom chat.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-source" class="slide level2">
<h2>The source</h2>
<blockquote>
<p>BALMER, F. E.—Dep. chief acctnt., G.P.O., E. Africa Prot., Mar., 1919; ch.&nbsp;acctnt., G.P.O., Kenya, Oct., 1919; ch.&nbsp;acctnt., Kenya-Uganda-Tanganyika post and tel. service, 1933; senr. dep. P.M.G., <mark>do.</mark>, 1935.</p>
</blockquote>
<p>85 volumes OCR’d, <strong>1867–1966</strong>. The Record of Services appears from <strong>1883</strong>. The same person returns in many editions.</p>
<div class="defs">
<div class="def">
<p><span class="def-term">What is OCR?</span> Optical character recognition turns a page image into text. These volumes were read by olmOCR, an open model that returns text blocks with their position on the page. OCR errors and printers’ errors look alike in the text; the scan decides.</p>
</div>
<div class="def">
<p><span class="def-term">What is “do.”?</span> <em>Ditto</em>: “the same as before”. The printer saved space by pointing back to an earlier place or office. A reader resolves it without thinking; a program has to be told.</p>
</div>
</div>
<aside class="notes">
<p>7–8. Keep OCR and source separate. A surprising date may be an OCR error or a printed error. Each record needs a volume and page reference; the packet’s source notes are not scans. The 1946 restart lacks the usual Record of Services.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="mark-up-balmer" class="slide level2">
<h2>Mark up Balmer</h2>
<div class="columns">
<div class="column" style="width:70%;">
<p>Choose <strong>entry 2</strong>. Tag the last two positions, their places and years.</p>
<p>Three minutes, then compare:</p>
<p><strong>What does “do.” inherit?</strong><br>
<strong>Where should that decision be recorded?</strong></p>
</div><div class="column" style="width:30%;">
<p><img data-src="images/qr-annotate.png" alt="QR code for the mark-up exercise" width="240"></p>
</div></div>
<p><strong>jimclifford.ca/imperial-careers-workshop/annotate/</strong></p>
<aside class="notes">
<p>8–13. Three minutes marking, one minute comparing, one minute debrief. Ask one room participant and the chat monitor for a reason. Paper users circle the corresponding words. Protect this time. The remaining entries are take-home practice.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="start-with-the-raw-ocr" class="slide level2">
<h2>Start with the raw OCR</h2>
<p>I showed <strong>Claude Code</strong> the text and discussed how to structure it.</p>
<blockquote>
<p>ch.&nbsp;acctnt., Kenya-Uganda-Tanganyika post and tel. service, 1933; senr. dep. P.M.G., do., 1935.</p>
</blockquote>
<div class="columns">
<div class="column" style="width:52%;">
<p><strong>Could Python do this on its own? What would the rules need to know?</strong></p>
<p><span class="small">Read a sample together. Agree what counts as a record and what fields to keep.</span></p>
<div class="source-meta"><b>edition</b> 1936 · <b>printed page</b> 614<br><b>OCR page index</b> 832 · <b>block</b> 11<br><b>bbox</b> [142, 2184, 827, 2334] · <b>category</b> text</div>
<p><span class="caption"><a href="outputs/structure/balmer-raw-ocr.json">Balmer’s original OCR block</a>: every record keeps its way back to the page</span></p>
</div><div class="column" style="width:48%;">
<div class="def">
<p><span class="def-term">What is Claude Code?</span> Anthropic’s coding agent. It runs on your own computer, reads the files you point it to, and writes and runs Python with your permission. You describe the task in plain language and judge the results; it reports what it did.</p>
<p>It is a commercial service, paid through a Claude subscription or per use. Here it <strong>built</strong> the pipeline; it did not read the 65,000 entries.</p>
</div>
</div></div>
<aside class="notes">
<p>13–14. Start with the actual working process: I opened the raw OCR with Claude Code and discussed whether a Python parser could do the job. The displayed excerpt is copied directly from the 1936 raw OCR block, before abbreviation expansion. The saved file includes the original bounding box, OCR page index 832, block index 11 and printed page 614. This is a walkthrough of the process, not a recovered chat transcript. Use the Balmer exercise they just completed: they already know that “do.” refers back to a place. Ask what the code would need to preserve to reach the same reading. Claude Code helped inspect the source, discuss the approach and write the scripts; the historian decided what the fields meant.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="too-irregular-for-regular-expressions-alone" class="slide level2 smaller">
<h2>Too irregular for regular expressions alone</h2>
<p><strong>A familiar historical problem: semi-structured data.</strong></p>
<p>The fields recur. The wording and relationships vary.</p>
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Source wording</th>
<th>What needs interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>“do., 1935”</td>
<td>Which preceding place does this posting inherit?</td>
</tr>
<tr class="even">
<td>“B. Honduras, Apl., 1898”</td>
<td>An appointment date; “B.” belongs to the place name</td>
</tr>
<tr class="odd">
<td>Trimen’s posts, 1867–1875 and 1869–1879</td>
<td>Two concurrent jobs, not one sequence</td>
</tr>
</tbody>
</table>
<p>Finding a year is easier than deciding <strong>what it dates</strong>.</p>
<div class="def">
<p><span class="def-term">What is a regular expression?</span> A pattern that matches text by its shape. <code>1[89]\d\d</code> finds every year from 1800 to 1999 in an entry. It cannot say which posting the year belongs to, or that “do.” points back three clauses.</p>
</div>
<aside class="notes">
<p>14–15. This is a source problem historians know well: recurring headings, names, dates and offices without a uniform sentence structure. OCR can add variation, but even perfectly transcribed entries contain elision, abbreviations, compound clauses and concurrent appointments. Regular expressions recognise specified patterns; increasingly elaborate rules did not cover the collection reliably. Python is still useful for segmentation, regular cases and checks. Explain the three rows: Balmer inherits the preceding service’s place; Blakely’s “B. Honduras” is British Honduras and April 1898 dates his clerkship; Trimen’s lecturer and British Museum posts overlap. The third example is in the saved Trimen source pack. The conclusion of our discussion was that Python rules alone were insufficient for this corpus. The hard part is binding the right position, place and date, not simply detecting a number.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="develop-the-hybrid-with-claude-code" class="slide level2">
<h2>Develop the hybrid with Claude Code</h2>
<p><span class="small">Agree the fields → try examples → decide which work belongs in each stage.</span></p>
<div class="flow">
  <div class="node blue"><b>1 · Python</b><span>Parse the regular entries. If any dated clause fails, refuse the whole entry.</span></div>
  <div class="arrow">→</div>
  <div class="node wide"><b>2 · Qwen reads</b><span>One entry in, one JSON record out. Binds position, place and dates across ditto, elided and concurrent clauses.</span></div>
  <div class="arrow">→</div>
  <div class="node blue"><b>3 · Python checks</b><span>Drop any place or year not in the source. Apply logged fixes for recurring errors.</span></div>
</div>
<div class="def">
<p><span class="def-term">What is Qwen?</span> A family of <strong>open-weight</strong> language models from Alibaba’s Qwen team. Open weight means the trained model can be downloaded and run on your own hardware, or reached through a hosted service. The structuring runs used <strong>Qwen3.6-35B-A3B</strong>: 35 billion parameters in all, about 3 billion active for each word-piece, so one GPU can run it quickly.</p>
</div>
<p><strong>Claude Code helped build the pipeline. Qwen read the entries.</strong></p>
<aside class="notes">
<p>15–16. Walk through the design as a division of work developed with Claude Code. First, keep Python where explicit rules are reliable; if a dated clause cannot be parsed, refuse the whole entry rather than silently omit it. Second, ask the model to interpret the difficult clauses within an agreed schema. Third, use Python to validate the result and log recurring corrections. One event has position, place, start/end years and an inheritance flag. Compare sample outputs with the OCR before increasing the run size. Claude Code was the interactive coding environment; Qwen3.6-35B was the model called by the corpus-reading script. The saved in-session runbook records how the reference examples were structured and validated.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="three-ways-to-run-qwen" class="slide level2">
<h2>Three ways to run Qwen</h2>
<p>The script sends each entry to a web address that speaks the OpenAI request format.<br>
<strong>Change one address to change where the model runs.</strong></p>
<div class="cards">
  <div class="card">
    <span class="kicker">Hosted service</span>
    <h4>OpenRouter</h4>
    <p>A broker for many models, open and commercial. Pay per token; no hardware.</p>
    <p class="fact">Used in June to compare several open models on the same 40 entries, scored against records Claude had structured in-session. Qwen3.6 came closest.</p>
  </div>
  <div class="card accent">
    <span class="kicker">Desktop GPU</span>
    <h4>NVIDIA DGX Spark</h4>
    <p>A desktop machine with 128 GB of memory shared with its GPU. vLLM serves the model on the local network.</p>
    <p class="fact">India Office List: 30,496 entries in 8.24 hours overnight. No per-request bill.</p>
  </div>
  <div class="card">
    <span class="kicker">Research cluster</span>
    <h4>Alliance: Narval, Nibi</h4>
    <p>Canada’s national research computing. Submit a batch job; it waits in a queue, starts the model, works through a file.</p>
    <p class="fact">Qwen3.8-27B judged 3,539 identity pairs in 35 minutes on one A100 GPU.</p>
  </div>
</div>
<div class="def">
<p><span class="def-term">What is vLLM?</span> Open-source software that loads a model onto a GPU and answers requests in the same format as the commercial services, so the same script works locally, on a cluster or through OpenRouter.</p>
</div>
<aside class="notes">
<p>16–17. One slide on infrastructure, because participants ask how to run the model. The script did not change between routes: it posts the system prompt and one entry to an OpenAI-compatible endpoint, and the base URL selects the service. The June bake-off (19 June, 40 entries against the in-session Opus reference set, reasoning off, temperature zero) ran several open models through OpenRouter; Qwen3.6-35B-A3B had the best event precision, place and honours scores. That reference set is provisional, not a gold standard. Production ran the same model on a DGX Spark desktop through vLLM, with no tunnel to depend on. The cluster example is later identity work, not structuring: Narval job 2430423, Qwen3.8-27B, one A100-40GB, 1.7 pairs a second. Cluster compute nodes have no internet, so the job serves the model inside the allocation. Any change of model or serving setup needs the sample audit again.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-prompt-is-the-decisions" class="slide level2">
<h2>The prompt is the decisions</h2>
<blockquote>
<p>Extract ONLY what is printed; never invent or infer facts.</p>
</blockquote>
<blockquote>
<p><strong>events:</strong> one object per distinct posting. EXPLODE compound clauses.</p>
</blockquote>
<p><strong>Place rule, summarised:</strong> keep printed wording; flag inheritance and stop at a stated transfer.</p>
<blockquote>
<p><strong>birth_year:</strong> only if printed. NEVER infer from the earliest career date.</p>
</blockquote>
<div class="def">
<p><span class="def-term">What is a system prompt?</span> The standing instructions sent with every one of the 65,000 entries. The entry itself follows as the user message. Every rule here exists because an earlier run broke it.</p>
</div>
<aside class="notes">
<p>17–19. This is what the discussion became: explicit instructions for the model inside the pipeline. The first, second and fourth quotations are from the saved prompt; the place line summarises its inheritance rule, including the stop at a stated transfer. Link to the exact prompt on step 3. Ask: would “defeated in an election” count as an office held? Leave that distinction in mind for Brewster.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="read-records-against-the-source" class="slide level2">
<h2>Read records against the source</h2>
<p><span class="small">Examples from the saved extraction audit, before rule fixes</span></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Source</th>
<th>Earlier output</th>
<th>Reading to preserve</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>“do., 1935”</td>
<td>place: “do.”</td>
<td>Inherit the preceding place</td>
</tr>
<tr class="even">
<td>“Apl., 1898”</td>
<td>birth_year: 1898</td>
<td>Date of the appointment</td>
</tr>
<tr class="odd">
<td>“KT. BACH. (1920)”</td>
<td>two honours</td>
<td>One knighthood</td>
</tr>
</tbody>
</table>
<div class="flow">
  <div class="node blue"><b>Sample</b><span>every tenth record, then spread across the corpus</span></div>
  <div class="arrow">→</div>
  <div class="node"><b>Read against the source</b><span>record beside the printed entry</span></div>
  <div class="arrow">→</div>
  <div class="node"><b>Sort findings</b><span>one-off, or a recurring pattern?</span></div>
  <div class="arrow">→</div>
  <div class="node after"><b>Logged rule</b><span>or individual review</span></div>
</div>
<p><strong>Batch run: 30,496 entries in 8.24 hours.</strong></p>
<aside class="notes">
<p>19–20. The model’s output still needs to be read against the source. These are historical extraction outputs used to teach that reading, not a report of current defects. All three audits were read by a model; the displayed examples were checked by hand. The detailed sample counts remain on step 3 for questions; they do not measure finished-graph accuracy. Ask participants to explain one reading before moving to the Balmer replay. Some findings need individual review rather than a general rule. The resulting hybrid processed 30,496 India Office entries in 8.24 hours, 25–26 June, with 16 workers, reasoning off and temperature zero. Put this scale result after the design and review process. If asked: 55 entries failed JSON validation, a format count rather than a count of inaccurate records.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="replay-a-past-correction" class="slide level2">
<h2>Replay a past correction</h2>
<p><strong>Balmer’s final event · saved extraction output</strong></p>
<div class="flow">
  <div class="node before"><b>Before</b><span>place: “do.”<br>place_inherited: true</span></div>
  <div class="arrow">→</div>
  <div class="node wide"><b>Rule</b><span>A literal ditto, and the previous event has a resolved place → inherit that place and log the reason</span></div>
  <div class="arrow">→</div>
  <div class="node after"><b>After</b><span>place: “Kenya-Uganda-Tanganyika”<br>place_inherited: true</span></div>
</div>
<p><strong>3 saved records · 12 events · 1 place corrected</strong></p>
<ul>
<li>Other events and fields unchanged.</li>
<li>Second run changes nothing.</li>
<li>No preceding resolved place? Leave it for review.</li>
</ul>
<p><a href="outputs/structure/ditto-fix-replay.json">Saved before-and-after records</a></p>
<aside class="notes">
<p>20–23. Use the saved replay; run python3 scripts/demo_ditto_fix.py only if time allows. No model or network is needed. Introduce this as a replay of an earlier correction using saved records. It is not a rerun of col_matching. The other eleven events and the saved Blakely and Connolly fields are unchanged: this demonstrates the scope of the ditto rule. The missing-predecessor checks are constructed tests, not historical records. Ask what else must be checked before applying this to the corpus: affected records, boundary cases, a fresh sample afterwards.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="clean-forty-editions-one-person" class="slide level2">
<h2>Clean: forty editions, one person</h2>
<p>A missed link leaves a fragmented career.<br>
A false merge can silently corrupt later analysis.</p>
<p><span class="gold">Ties resolve to no merge.</span></p>
<div class="flow">
  <div class="node blue"><b>199,099</b><span>printed entries, Colonial Office List</span></div>
  <div class="arrow">→</div>
  <div class="node"><b>Strong rules</b><span>same name and birth year, or a shared dated event</span></div>
  <div class="arrow">→</div>
  <div class="node"><b>Clusters</b><span>same forename, same surname ending, so OCR variants meet</span></div>
  <div class="arrow">→</div>
  <div class="node"><b>Dossiers</b><span>a model argues each hard case; review queue for the rest</span></div>
  <div class="arrow">→</div>
  <div class="node after"><b>27,526</b><span>person records, with a ledger of reasons</span></div>
</div>
<div class="defs">
<div class="def">
<p><span class="def-term">Dossier</span> Every version of every biography in a cluster, laid out for one decision: births, schools, honours, the full dated career.</p>
</div>
<div class="def">
<p><span class="def-term">Ledger</span> An append-only file of merge decisions, each with its reason, so any one can be revisited and reversed.</p>
</div>
</div>
<aside class="notes">
<p>23–25. 199,099 printed CO entry instances resolved into 27,526 person records. The ledger makes decisions revisitable; do not call false merges irreversible. Explain a dossier as the source evidence for both candidates, gathered in one place.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="decide-before-the-answer" class="slide level2">
<h2>Decide before the answer</h2>
<div class="cards" style="font-size:0.78em">
  <div class="card"><span class="kicker">One edition</span><h4>ABERY, Joseph</h4><p>M.B.C.M.</p><p>1867 · Ceylon · assistant colonial surgeon</p></div>
  <div class="card"><span class="kicker">Six editions</span><h4>CARBERY, Joseph</h4><p>M.B.C.M.</p><p>1867 · Ceylon · assistant colonial surgeon</p></div>
</div>
<p><strong>Merge, keep apart, or review? What evidence decides it?</strong></p>
<div class="fragment">
<p>The ledger merges them: consistent name and qualification, an identical dated appointment, and a plausible OCR loss. Preserve both entries and the reason.</p>
</div>
<aside class="notes">
<p>25–28. Give 30 seconds to decide; room and Zoom use the same three words. Then reveal. Qualification is not an honour. Checking the scan for the lost letters would strengthen the decision. A common first name alone is insufficient.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="keep-apart-keep-the-evidence" class="slide level2">
<h2>Keep apart; keep the evidence</h2>
<div class="cards" style="font-size:0.78em">
  <div class="card"><span class="kicker">Born 1836</span><h4>A’BECKETT, Thomas</h4><p>Lincoln’s Inn</p><p>Victorian judge · knighted 1909</p></div>
  <div class="card"><span class="kicker">Born 1898</span><h4>BECKETT, Thomas Rumbold</h4><p>Judd School</p><p>Nigerian telegraph engineer</p></div>
</div>
<p>Different schools and careers, not only different birth years. <strong>Keep apart.</strong></p>
<div class="def">
<p><span class="def-term">The merge rules, in brief</span> Merge only on positive evidence: an overlapping dated event, a shared honour with its year, near-identical education, or an OCR variant with a consistent career. Birth year alone never splits: it is often misread. Different spelled forenames keep people apart.</p>
</div>
<aside class="notes">
<p>28–30. A birth-year discrepancy alone is not a universal veto: it may be OCR. Here the whole dossiers differ. The supporting page has more clusters; do not run all four aloud.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="ground-retrieve-read-decide" class="slide level2">
<h2>Ground: retrieve, read, decide</h2>
<p>Every plotted posting needs a place.<br>
Every shared person identifier asserts an identity.</p>
<div class="flow">
  <div class="node blue"><b>Mention</b><span>“Victoria, 1912”</span></div>
  <div class="arrow">→</div>
  <div class="node"><b>Retrieve</b><span>candidate items from a search tool</span></div>
  <div class="arrow">→</div>
  <div class="node"><b>Read</b><span>type, dates, location against the career</span></div>
  <div class="arrow">→</div>
  <div class="node after"><b>Decide and record</b><span>supported · unresolved · wrong, with evidence and date</span></div>
</div>
<p>No supported match? Keep the local identifier.</p>
<div class="defs">
<div class="def">
<p><span class="def-term">What is Wikidata? A QID?</span> A free, shared knowledge base. Each item has an identifier: Q plus a number. Q1800510 is Philip Wodehouse. Linking to it lets other projects join their data to ours.</p>
</div>
<div class="def">
<p><span class="def-term">What is MCP?</span> Model Context Protocol: a standard way to hand a model a tool, such as a Wikidata search. The answer comes back as retrieved evidence, not from the model’s memory.</p>
</div>
</div>
<aside class="notes">
<p>30–31. An identifier’s existence is not evidence that it belongs to this mention. Introduce MCP simply as a lookup tool the agent can use; the protocol is not today’s lesson.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="live-three-searches" class="slide level2">
<h2>Live: three searches</h2>
<ol type="1">
<li><strong>Henry Trimen</strong> — botanist, Ceylon, Peradeniya.</li>
<li><strong>Ferdinando Hamlyn Price</strong> — a rare name, compatible dates, thin career evidence.</li>
<li><strong>Elwood D’Arcy Tibbits</strong> — no plausible result in the saved search.</li>
</ol>
<p>Supported · unresolved · wrong</p>
<div class="def">
<p><span class="def-term">Reading a candidate item</span> Is it a human? Do the birth and death dates fit the career? Do occupation, positions held and places match the entry? One contradiction outweighs a matching name.</p>
</div>
<aside class="notes">
<p>31–34. Trimen: read statements before accepting. Price: ask participants before stating your decision; accepting with recorded limitations or seeking another source is defensible. Tibbits: record the search, do not claim no item exists. Use saved answer-key.md if live lookup fails. Cap live work at three minutes.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="a-saved-run-without-lookup-tools" class="slide level2">
<h2>A saved run without lookup tools</h2>
<div class="big">
<p><span class="gold">0 of 16</span></p>
</div>
<p>person identifiers correct in the saved Gemini 3.8 Flash run.</p>
<p>Fluent biographies. Plausible-looking numbers. Wrong items.</p>
<p><strong>A name understood is not an identifier verified.</strong></p>
<div class="def">
<p><span class="def-term">Why memory fails here</span> A QID is an arbitrary number. A model can learn that officials have QIDs, and what such numbers look like, without learning which number belongs to whom. Without a lookup tool it writes a plausible number.</p>
</div>
<aside class="notes">
<p>34–35. Twenty entries; sixteen identifiers supplied, four declined. This is one run, not a general model ranking. Saved outputs are sufficient; do not start a second live demo.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="same-entries-different-workflows" class="slide level2">
<h2>Same entries, different workflows</h2>
<p><strong>Saved experiment · twenty entries</strong></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Saved run</th>
<th>Subject links accepted in review</th>
<th>Elapsed</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Gemini 3.8 Flash, no tools</td>
<td>0 of 16 supplied</td>
<td>under 5 min</td>
</tr>
<tr class="even">
<td>Claude Opus 5.5, web retrieval</td>
<td>16 of 16 supplied</td>
<td>about 20 min</td>
</tr>
<tr class="odd">
<td>GPT Astra 6, web retrieval</td>
<td>16 of 16 supplied</td>
<td>about 27 min</td>
</tr>
</tbody>
</table>
<p>The pipeline supplied <strong>12</strong> links; the review supported all 12.</p>
<p>Check retrieved evidence against the career’s dates and context.</p>
<aside class="notes">
<p>35–36. These are saved experimental outputs, not current atlas results. Different models and tools: not a controlled test of retrieval alone. The site keeps the detailed place table with its different denominators and the historical Victoria mismatch. Astra’s 155 label/alias checks are not 155 historically correct matches. Hold Harris’s specific discrepancy back for R8.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="two-jobs-measure-their-costs" class="slide level2">
<h2>Two jobs; measure their costs</h2>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Job</th>
<th>What the project used</th>
<th>What to measure</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Write and repair the pipeline</td>
<td>Frontier coding agent</td>
<td>Session cost and historian time</td>
</tr>
<tr class="even">
<td>Read the collection</td>
<td>Open model (Qwen) on a desktop GPU or cluster</td>
<td>Throughput, GPU time, failures and audit time</td>
</tr>
<tr class="odd">
<td>Review hard cases</td>
<td>Retrieval with a capable model</td>
<td>Lookup cost and time per case</td>
</tr>
</tbody>
</table>
<p>27 minutes / 20 entries ≈ 80 seconds each.<br>
<strong>About 25 days if run serially for 27,526 entries at that rate.</strong></p>
<p>Start with twenty records. No cluster needed for the first trial.</p>
<div class="def">
<p><span class="def-term">Frontier and open-weight</span> <em>Frontier</em>: the most capable models, from Anthropic, OpenAI and Google, reached only through their services. <em>Open-weight</em>: models whose trained weights can be downloaded and run anywhere. Different properties, not opposites.</p>
</div>
<aside class="notes">
<p>36–38. The 25 days is a serial extrapolation, not a forecast or invoice. Caching and concurrency change throughput. Campus computing is not free infrastructure, even without a per-request bill. Hosted models are a route for participants without a GPU. Measure on their sample rather than promising a dollar total. Keep this slide: attendees miss the parallel cost/model session.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="what-reading-the-corpus-costs" class="slide level2 smaller">
<h2>What reading the corpus costs</h2>
<p>Measured on a random sample of 2,000 India Office entries and 2,000 Qwen records:</p>
<div class="stats">
  <div class="stat"><span class="num">~640</span><span class="lbl">tokens read per entry: 470 of prompt, about 150 of entry</span></div>
  <div class="stat"><span class="num">~330</span><span class="lbl">tokens written per entry: the JSON record</span></div>
  <div class="stat"><span class="num">30,496</span><span class="lbl">India Office List entries</span></div>
</div>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Route</th>
<th>Price</th>
<th>30,496 entries</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>OpenRouter, Qwen3.8-27B, 8 Oct</td>
<td>$0.0239 read / $2.175 written per million tokens (50% promotion)</td>
<td><strong>≈ $22</strong></td>
</tr>
<tr class="even">
<td>Same model, regular price</td>
<td>about twice the promotion</td>
<td><strong>≈ $45</strong></td>
</tr>
<tr class="odd">
<td>DGX Spark desktop, Qwen3.6 (as run)</td>
<td>the machine and its electricity</td>
<td><strong>8.24 hours</strong>, no bill per request</td>
</tr>
</tbody>
</table>
<p>Almost all of the hosted cost is the <strong>writing</strong>: the record the model returns, not the text it reads.</p>
<div class="def">
<p><span class="def-term">What is a token?</span> The unit models read and write in, roughly three-quarters of a word. Services charge per million tokens, with separate prices for reading (input) and writing (output).</p>
</div>
<aside class="notes">
<p>38–40. Worked estimate, not an invoice. Token counts use the Qwen tokenizer on a random 2,000 India Office entry instances and 2,000 saved Qwen records; input is the 471-token system prompt plus the entry and a small chat-template allowance. 30,496 × 640 ≈ 19.5 million tokens read ≈ $0.47; 30,496 × 330 ≈ 10 million written ≈ $22. Add retries (four allowed) and failures. The OpenRouter price was 50% off on 8 October 2026; check the current price on the day. Qwen3.8-27B was not the structuring model: switching models needs the sample audit again. For comparison, the June bake-off estimated about $13 for the Colonial Office List on Qwen3.6 through OpenRouter at June prices. The desktop has no per-request bill, but the machine, power and the historian’s time are real costs.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="a-past-repair-which-victoria" class="slide level2">
<h2>A past repair: which Victoria?</h2>
<p>Brewster’s entry: <strong>“defeated by Sir Richard McBride, in Victoria, 1912.”</strong></p>
<p>An earlier atlas placed a British Columbia politician in Australia.</p>
<div class="chips"><span>Colony of Victoria, Australia</span><span class="hit">Victoria, British Columbia</span><span>Victoria, Hong Kong</span><span>Victoria, Seychelles</span><span>Victoria, Labuan</span></div>
<p><span class="caption">One printed word; several imperial places with that name.</span></p>
<div class="flow">
  <div class="node before"><b>Before</b><span>One “Victoria” lookup, reused for every entry that printed the word → Australia</span></div>
  <div class="arrow">→</div>
  <div class="node wide"><b>Completed fix</b><span>Resolve the place per person, from the surrounding career: McBride, the legislative assembly, British Columbia</span></div>
  <div class="arrow">→</div>
  <div class="node after"><b>After</b><span>Victoria, British Columbia; every affected entry re-emitted</span></div>
</div>
<aside class="notes">
<p>40–42. State that this is a completed repair before discussing the old result. Explain the per-person resolver and the identifier-key bug it exposed. Both corpora were re-emitted. Ask what evidence selects British Columbia: the surrounding career clauses. The supporting page retains South Africa and Baluchistan as further historical examples.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="a-past-repair-what-counts-as-an-event" class="slide level2">
<h2>A past repair: what counts as an event?</h2>
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Source</th>
<th>Earlier graph, after the place fix</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Defeated</strong>, Victoria, 1912</td>
<td>Legislative assembly member for Victoria, <strong>1912–1916</strong></td>
</tr>
</tbody>
</table>
<p><strong>Would you accept this office-held assertion?</strong></p>
<div class="fragment">
<p>A defeat does not establish an appointment. <strong>Repaired:</strong> preserve the defeat as an event; remove the office-held assertion. Check other defeat clauses.</p>
</div>
<p>A plausible map can conceal a misread source.</p>
<aside class="notes">
<p>42–44. The table is a saved stage in the repair, before the event correction. Pause for a room/chat verdict before revealing the completed repair. The public graph now types this as an electoral defeat and removes the held-role edge. The same check catches other explicit electoral-defeat events. Use this to teach the difference between recording an event and asserting an office held.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="what-a-map-cannot-check" class="slide level2">
<h2>What a map cannot check</h2>
<div class="cards">
  <div class="card accent"><span class="kicker">The map shows</span><h4>What looks wrong</h4><p>A politician in the wrong hemisphere. A jump no career could make. Two nodes with one name.</p></div>
  <div class="card warn"><span class="kicker">The map hides</span><h4>What is missing</h4><p>A missed link leaves two plausible short careers. An ungrounded posting simply vanishes. A false merge can look like an ordinary career.</p></div>
</div>
<p>Use a labelled sample, including the cases the pipeline rejected.</p>
<p><strong>Check both the repaired cases and other records the rule changed.</strong></p>
<aside class="notes">
<p>44–46. Explain why source sampling complements visual inspection: a missing record may produce no visible anomaly. Include accepted and rejected decisions in the review design. Keep the historical audit figures on the supporting pages for questions; focus here on how participants would check their own data.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="three-decisions-with-reasons" class="slide level2">
<h2>Three decisions, with reasons</h2>
<p><strong>Work from the saved teaching cases.</strong></p>
<div class="columns">
<div class="column" style="width:70%;">
<p><strong>R1</strong> · Blakely: accept the record?<br>
<strong>R3</strong> · Abery / Carbery: accept the merge?<br>
<strong>R8</strong> · Harris: accept a link with a disputed birth year?</p>
<p>Decide. Give the evidence. Say what you would check next.</p>
<p><strong>Six minutes working; four minutes discussing R8.</strong></p>
</div><div class="column" style="width:30%;">
<p><img data-src="images/qr-review.png" alt="QR code for the three-decision exercise" width="240"></p>
</div></div>
<p><strong>jimclifford.ca/imperial-careers-workshop/review/</strong></p>
<aside class="notes">
<p>46–56. Introduce these as saved proposals for practising decisions, not a live queue of atlas errors. The site displays the core cases first; the other five are further practice. Do not reveal the Harris answer until participants have decided. Zoom users select R8 and copy its decision and reason. Ask for an accept and an unresolved rationale; both can be defensible. Separate identity confidence from permission to change a source field. Printed handout page 2 has the same three decisions.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="your-first-twenty-records" class="slide level2">
<h2>Your first twenty records</h2>
<ul>
<li>Show the coding agent your raw text, including a hard case.</li>
<li>Discuss what Python rules can handle and what needs interpretation.</li>
<li>Agree a schema and review two examples against the source.</li>
<li>Build the hybrid; run a small sample and record corrections.</li>
<li>Rerun, check what changed, then measure a larger run.</li>
</ul>
<p><strong>Write one sentence: what counts as a record in your collection?</strong></p>
<aside class="notes">
<p>56–60. One minute for this sentence; invite one response and questions. The take-home prompt and cost worksheet are on step 7. Close by pointing to the saved prompt, replay and exercises, not by listing every tool again.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="keep-the-decision-with-the-evidence" class="slide level2" data-background-image="images/atlas-screenshot.png" data-background-opacity="0.1">
<h2>Keep the decision with the evidence</h2>
<p>Structure · Clean · Ground</p>
<p>Build. Extract. Visualise. See. Fix. Rerun.</p>
<p><img data-src="images/qr-site.png" alt="QR code for the workshop site" height="180"></p>
<p><strong>jimclifford.ca/imperial-careers-workshop</strong><br>
Exercises, worked answers, prompt, replay and glossary.</p>


</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p>jimclifford.ca/imperial-careers-workshop</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="site_libs/revealjs/plugin/search/search.js"></script>
  <script src="site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'fade',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'fade',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1280,

        height: 720,

        // Factor of the display size that should remain empty around the content
        margin: 8.0e-2,

        math: {
          mathjax: 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script>
    // Site QR code on the title slide, for the room and for Zoom screens.
    (function () {
      var t = document.getElementById('title-slide');
      if (!t) return;
      var img = document.createElement('img');
      img.src = 'images/qr-site.png';
      img.alt = 'QR code for jimclifford.ca/imperial-careers-workshop';
      img.style.cssText = 'position:absolute;right:0;bottom:40px;width:190px;height:190px;margin:0';
      t.appendChild(img);
    })();
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
    window.document.addEventListener("DOMContentLoaded", function (event) {
      const toggleBodyColorMode = (bsSheetEl) => {
        const mode = bsSheetEl.getAttribute("data-mode");
        const bodyEl = window.document.querySelector("body");
        if (mode === "dark") {
          bodyEl.classList.add("quarto-dark");
          bodyEl.classList.remove("quarto-light");
        } else {
          bodyEl.classList.add("quarto-light");
          bodyEl.classList.remove("quarto-dark");
        }
      }
      const toggleBodyColorPrimary = () => {
        const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
        if (bsSheetEl) {
          toggleBodyColorMode(bsSheetEl);
        }
      }
      toggleBodyColorPrimary();  
      const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
      tabsets.forEach(function(tabset) {
        const tabby = new Tabby('#' + tabset.id);
      });
      const isCodeAnnotation = (el) => {
        for (const clz of el.classList) {
          if (clz.startsWith('code-annotation-')) {                     
            return true;
          }
        }
        return false;
      }
      const onCopySuccess = function(e) {
        // button target
        const button = e.trigger;
        // don't keep focus
        button.blur();
        // flash "checked"
        button.classList.add('code-copy-button-checked');
        var currentTitle = button.getAttribute("title");
        button.setAttribute("title", "Copied!");
        let tooltip;
        if (window.bootstrap) {
          button.setAttribute("data-bs-toggle", "tooltip");
          button.setAttribute("data-bs-placement", "left");
          button.setAttribute("data-bs-title", "Copied!");
          tooltip = new bootstrap.Tooltip(button, 
            { trigger: "manual", 
              customClass: "code-copy-button-tooltip",
              offset: [0, -8]});
          tooltip.show();    
        }
        setTimeout(function() {
          if (tooltip) {
            tooltip.hide();
            button.removeAttribute("data-bs-title");
            button.removeAttribute("data-bs-toggle");
            button.removeAttribute("data-bs-placement");
          }
          button.setAttribute("title", currentTitle);
          button.classList.remove('code-copy-button-checked');
        }, 1000);
        // clear code selection
        e.clearSelection();
      }
      const getTextToCopy = function(trigger) {
          const codeEl = trigger.previousElementSibling.cloneNode(true);
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
      }
      const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
        text: getTextToCopy
      });
      clipboard.on('success', onCopySuccess);
      if (window.document.getElementById('quarto-embedded-source-code-modal')) {
        const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
          text: getTextToCopy,
          container: window.document.getElementById('quarto-embedded-source-code-modal')
        });
        clipboardModal.on('success', onCopySuccess);
      }
        var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
        var mailtoRegex = new RegExp(/^mailto:/);
          var filterRegex = new RegExp('/' + window.location.host + '/');
        var isInternal = (href) => {
            return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
        }
        // Inspect non-navigation links and adorn them if external
     	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
        for (var i=0; i<links.length; i++) {
          const link = links[i];
          if (!isInternal(link.href)) {
            // undo the damage that might have been done by quarto-nav.js in the case of
            // links that we want to consider external
            if (link.dataset.originalHref !== undefined) {
              link.href = link.dataset.originalHref;
            }
              // target, if specified
              link.setAttribute("target", "_blank");
              if (link.getAttribute("rel") === null) {
                link.setAttribute("rel", "noopener");
              }
          }
        }
      function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
        const config = {
          allowHTML: true,
          maxWidth: 500,
          delay: 100,
          arrow: false,
          appendTo: function(el) {
              return el.closest('section.slide') || el.parentElement;
          },
          interactive: true,
          interactiveBorder: 10,
          theme: 'light-border',
          placement: 'bottom-start',
        };
        if (contentFn) {
          config.content = contentFn;
        }
        if (onTriggerFn) {
          config.onTrigger = onTriggerFn;
        }
        if (onUntriggerFn) {
          config.onUntrigger = onUntriggerFn;
        }
          config['offset'] = [0,0];
          config['maxWidth'] = 700;
        window.tippy(el, config); 
      }
      const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
      for (var i=0; i<noterefs.length; i++) {
        const ref = noterefs[i];
        tippyHover(ref, function() {
          // use id or data attribute instead here
          let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
          try { href = new URL(href).hash; } catch {}
          const id = href.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note) {
            return note.innerHTML;
          } else {
            return "";
          }
        });
      }
      const findCites = (el) => {
        const parentEl = el.parentElement;
        if (parentEl) {
          const cites = parentEl.dataset.cites;
          if (cites) {
            return {
              el,
              cites: cites.split(' ')
            };
          } else {
            return findCites(el.parentElement)
          }
        } else {
          return undefined;
        }
      };
      var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
      for (var i=0; i<bibliorefs.length; i++) {
        const ref = bibliorefs[i];
        const citeInfo = findCites(ref);
        if (citeInfo) {
          tippyHover(citeInfo.el, function() {
            var popup = window.document.createElement('div');
            citeInfo.cites.forEach(function(cite) {
              var citeDiv = window.document.createElement('div');
              citeDiv.classList.add('hanging-indent');
              citeDiv.classList.add('csl-entry');
              var biblioDiv = window.document.getElementById('ref-' + cite);
              if (biblioDiv) {
                citeDiv.innerHTML = biblioDiv.innerHTML;
              }
              popup.appendChild(citeDiv);
            });
            return popup.innerHTML;
          });
        }
      }
    });
    </script>
    

</body></html>